### ISSUE TITLE
Release 1.7.0 not available

### ISSUE THREAD

**Issue by riteshtendulkar** [mpetruska/uk-modulo-scala#10]
Hello, latest updates include changes to vocalink spec 4.7. The homepage of the project mentions these are available as release 1.7.0, but the releases page doesn't show it? (Last available is 1.6.0. released in Sept 17). Am I missing something?

**Comment by mpetruska** [comment]
Hi, sorry, forgot to tag the version. The artifacts should be available from [Maven Central Repository](https://search.maven.org/#search%7Cga%7C1%7Cuk-modulo-scala).

**Comment by mpetruska** [comment]
Tagged, closing issue. Thanks for reporting.
