### ISSUE TITLE
Enable the library to be cross-compiled to Scala 2.13

### ISSUE THREAD

**Issue by lewisc2303** [mpetruska/uk-modulo-scala#29]
At the moment the library is compatible with 2.10, 2.12 and 2.13. 
Would be good to get a version working for 2.13

**Comment by LydiaSkuse** [comment]
have made a PR for this, as well as updating the spec. need 👀 from @mpetruska 

https://github.com/mpetruska/uk-modulo-scala/pull/30

**Comment by mpetruska** [comment]
The PR is merged, thank you very much for the help. Please stand by for the next release.
